### ISSUE TITLE
POMOCY MENEL MI ZROBIŁ NAPAD!

### ISSUE THREAD

**Issue by boprr** [jakub-swiniarski/napad-na-fabryke-jaboli#1]
![image](https://github.com/jakub-swiniarski/napad-na-fabryke-jaboli/assets/85123713/7296b258-0a79-4dfc-98e7-e7d90cccb8af)

**Comment by boprr** [comment]
panie pomóż no

**Comment by jakub-swiniarski** [comment]
Niestety nie jestem w stanie pomóc Ci w sprawie napadu menela na Twoją posesję.

**Comment by boprr** [comment]
Będziesz klepany

**Comment by boprr** [comment]
Brek menel zamieszkał mi przed domem
