### ISSUE TITLE
Panie

### ISSUE THREAD

**Issue by Czarkowski16** [jakub-swiniarski/napad-na-fabryke-jaboli#2]
Panie dobry menel jakiś zrobił mi gówno jak odpaliłem tą grę co mam zrobić

**Comment by jakub-swiniarski** [comment]
Szanowny Panie,
Jako twórca darmowego i open-source'owego software'u nie jestem odpowiedzialny za wszelkiego rodzaju wypadki losowe związane z menelami. Nie jestem w stanie Panu pomóc.
